backend:
  name: git-gateway
  branch: main

media_folder: "public"

publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publication Date", name: "pubDate", widget: "datetime" }
      - { label: "Hero Image", name: "heroImage", widget: "image" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Abstract", name: "abstract", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {blog_link: "Blog Link", name: "blog_link", widget: "string" }


  - name: "testimonials"
    label: "Testimonials"
    folder: "src/content/testimonials"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - { label: "Title", name: "name", widget: "string" }
      - { label: "CustomerName", name: "position", widget: "string" }
      - { label: "Quote", name: "quote", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }


  - name: "resources"
    label: "Resources"
    folder: "src/content/resources"
    extension: "json"
    format: "json"
    create: true
    slug: "{{slug}}"
    fields:
      # add a field to order the resources id integer
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Secondary Title", name: "secondarytitle", widget: "string" }
      - label: "Items"
        name: "items"
        widget: "list"
        fields:
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Logo", name: "logo", widget: "image" }
          - { label: "Link", name: "link", widget: "string" }


  - name: "faqs"
    label: "FAQs"
    folder: "src/content/faqs"
    extension: "json"
    format: "json"
    create: true
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Questions"
        name: "questions"
        widget: "list"
        fields:
          - { label: "Question", name: "question", widget: "string" }
          - { label: "Answer", name: "answer", widget: "string" }

